### ISSUE TITLE
NDVI Calculation R Studio crashes when running index_cube

### ISSUE THREAD

**Issue by stpCES** [mapme-initiative/mapme.vegetation#5]
Next issue, sorry.
I've tried to continue with the NDVI calculation. 
Using your example or my changed parameters doesn't matter. It always aborts the whole R session when running the index_cube command.

**Comment by goergen95** [comment]
I experienced the same behavior on Windows machines before. The issue seems to be an unidentified source of error when calling `gdalcubes::create_image_collection()`. I have not experienced the same behavior under Ubuntu. You could try to use a different OS. Unfortunately, I currently do not have the resource to dig further into this...

**Comment by goergen95** [comment]
Could you somehow share your processing script an AOI (e.g. via mail)?

**Comment by stpCES** [comment]
I send you an email with the script and AoI

**Comment by stpCES** [comment]
Under Ubuntu index cube is running
